### ISSUE TITLE
Mod format

### ISSUE THREAD

**Issue by hunterboerner** [hunterboerner/oknow#1]
Thoughts?

```toml
[mod]
name = "buildcraft"
authors = ["Person 123"]
description = """
BuildCraft lets you build and craft all at once! Something something
builcraft. Blah words minecraft. Mods. 123 this is buildcraft.
"""
version = "7.1.2"
source = "https://github.com/BuildCraft/BuildCraft.git"

[[files]]
type = "universal"
url = "http://example.com/file-7.1.2.jar"
sha = "7bb9124e8034c3e50affa2893e02dd94348736ec"
rev = "7.1.2"

[dependencies]
minecraft = "1.8.0"
forge = "[11.14.3.1234,)"
```
/cc @aantron
